csc/Hanlon

core/engine.rb
web/api/api_image_v1.rb
web/api/api_model_v1.rb

This pull request adds code to check and see if a model is in use with a policy before removing the model. If it is in use with a policy, then an error message is returned and the model is not removed (as is the case with removal of images that are in use with a model, removing a model that is in use with a policy can create an error condition where policies exist that reference non-existent models). While making the modifications to support this additional check in the model DELETE method, the code for the image slice (in the Engine class) was also modified slightly so that (like the code in the new `remove_model` method we added to this class) the UUIDs of **all** of the models that use a given image are mentioned in the error message that is returned when trying to remove an image that …

Fixes #311 (Removal of model doesn't check if it's in use by a policy)

---

core/image_service.rb
core/image_service/base.rb
core/image_service/microkernel.rb
core/image_service/os_install.rb
core/image_service/vmware_hypervisor.rb
core/image_service/windows_install.rb
core/image_service/xenserver_hypervisor.rb
core/model/ubuntu.rb
core/slice/image.rb
util/utility.rb
web/api/api_image_v1.rb

The changes in this PR add the ability to add images contained in a Windows ISO to Hanlon using the `hanlon image add` command and remove the resulting images from Hanlon using the standard `hanlon image remove` command. In short, the changes are as follows:
* Adds support for creation of images from a Windows ISO using the `hanlon image add` command. First, the ISO file is 'unpacked', and a **hidden** image is created that references the extracted contents of that ISO. After that, the `wiminfo` command is used to extract a list of named **subimages** from the `install.wim` file extracted from that ISO, and a set of **linked** images are created that reference the hidden image that was created in the first step. Finally, the list of non-hidden images that were created by the `hanlon image …

Adds Windows support to the image slice

---

core/config/server.rb
web/app.rb

This PR adds a new `/static` endpoint to Hanlon that can be mapped to a directory in the Hanlon filesystem using a newly defined `hanlon_static_path` in the Hanlon server configuration file (which should be mapped to the directory containing the static content that should be served up by Hanlon). The code in this PR will catch errors where the file does not exist or is not a regular file and will return a 404 error in those cases.  An example of the use of this new functionality is the following curl command:
```bash
$ curl -g http://192.168.78.2:8026/hanlon/api/v1/static/COPYING
GNU GENERAL PUBLIC LICENSE
Version 2, June 1991
Copyright (C) 1989, 1991 Free Software Foundation, Inc.
51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
Everyone is permitted to copy and distribute …
```

Adds ability to serve up static content

---

web/app.rb

This pull request fixes how requests for components from a Windows image are handled (retrieving the component from a directory based on the image path and the UUID of the base image rather than the UUID of the image itself). Without this change, attempts to retrieve the components of a non-base image will fail with a 500 error.

Fixes #320 (Request for component from a Windows image fails)

---

core/model/debian.rb
core/model/opensuse_12.rb
core/model/redhat.rb
core/model/sles_11.rb
core/model/ubuntu.rb

Previously calls to the `sources_fix` callback made during execution of the post-install boot process in the Debian and Ubuntu models would fail because the `sources_fix` callback actually incorrectly defined as the `source_fix` callback in the underlying models. This PR fixes that error (and removes this callback from the `redhat`, `sles11`, and `opensuse_12` models where it is never used).

Slight refactoring to ensure calls to 'sources_fix' callback succeed

---

scripts/winpe/build-winpe.ps1
scripts/winpe/hanlon-discover.ps1

The build-winpe.ps1 creates the required WinPE to provision a Windows 2012
R2 server.  The hanlon-discover.ps1 retrieves from the registry the
vendor specific options and determines the SMBIOS uuid to grab the hanlon
image uuid and active_model/policy uuid.
Resolves issue #323

Required PowerShell scripts to add Windows provisioning

---

scripts/winpe/build-winpe.ps1

Added a workaround if chocolatey is unable to install the ADK.  The workaround consists of executing the adksetup.exe and executing it with the required parameters to just install WinPE.  If the workaround fails the script exits.  If there is a failure with mounting the WinPE image, I also added additional exception handling to exit upon failure.

Fixes #326 - Choco Install Failure

---

Dockerfile
hanlon.gemspec

These two files each contain a Hanlon version that should have been updated prior to yesterday's release; this PR updates these two files to reflect the new version number.

Fixing version number in DockerFile and hanlon.gemspec

---

scripts/hanlon_docker.sh

The script incorrectly referenced paths inside the container which resulted in the local development sources not being used by the container.  Also, the protocol should be specified for the ports on the ipxe container.
Fixes #333

Corrects path references and protocol spec in hanlon_docker.sh

---

.gitignore
Gemfile.lock

Gemfile.lock should be in version control. This will keep gem versions consistent between development and production deployment.
http://bundler.io/v1.8/rationale.html#checking-your-code-into-version-control
Fixes #331

.gitignore Update for Gemfile.lock

---

core/config/server.rb
core/model/coreos.rb
core/model/coreos/boot_install.erb
core/model/coreos/boot_local.erb
core/model/coreos/cloud-config.erb
core/model/coreos/kernel_args.erb
core/model/coreos_stable.rb
core/model/model_dep.rb

To install a CoreOS node, set up hanlon with the following commands (tested in VirtualBox, hence the tag. YMMV):
```
hanlon image add -t mk -p /vagrant/isos/hnl_mk_dev-image.2.0.1.iso
hanlon image add -t os -p /vagrant/isos/coreos_557.iso -v 557
IMAGE_UUID=$(hanlon image | grep coreos | awk '{print $1}')
hanlon model add --template coreos_stable --label install_coreos --image-uuid $IMAGE_UUID -o /vagrant/hanlon-config/model.yaml
MODEL_UUID=$(hanlon model | grep coreos | awk '{print $5}')
hanlon policy add --template linux_deploy --label coreos --model-uuid $MODEL_UUID  --broker-uuid=none --tags OracleCorporation -e true
```
For `model.yaml` use this:
```
hostname_prefix: "coreosnode"
domainname: localdomain
cloud_config:
coreos:
units:
- name: etcd.service
command: start
- name: …
```

CoreOS Model

---

Dockerfile

Moving the version of ruby installed back to 1.9.3 temporarily.
1.9.3 has been tested with the current gem set.
Dockerfile build tested locally.
Fixes #342

Fixes #342 - Rolling back ruby version in Dockerfile

---

core/engine.rb
core/policy/base.rb
core/slice/policy.rb
web/api/api_policy_v1.rb

The changes in this PR add code to Hanlon that allows for the use of either a `,` or an `|` character as a separator in the tag strings used to specify the tags for a policy when when creating/updating policies. The rules are relatively simple:
* if a `,` character is used, an 'and' comparison of the tags in a node with the tags in a policy will be used to see if a given policy matches a given node (i.e. all of the policy tags must match tags assigned to the node or there is no match between the node and the policy)
* if an `|` character is used, an 'or' comparison of the tags in a node with the tags in a policy will be used to see if a given policy matches a given node (i.e. at least one of the policy tags must match with a tag assigned to the node or there is no match between the node …

Resolves #340 (Add ability to specify **logical or** of tags for policies)

---

scripts/hanlon-client.sh
scripts/hanlon_docker.sh

The script used to manage hanlon docker containers for development is
updated to not require hard-coded IP addresses.  This makes the script
much more portable between development environments.  Additionally, a
new 'pull' option has been added to update the local docker images with
the latest available on the Docker Hub repository.
A new script has been added to simplify using a container to run the hanlon
client.

Update hanlon docker scripts

---

core/persist/memory_plugin.rb

This PR fixes problems with the handling of symbols in serialization/deserialization process for Hanlon's in-memory datastore. With these changes in place, Issue #350 should be resolved.

Fixes #350 (memory plugin for persistence returns 'strings' for :symbols)

---

core/model/coreos.rb
core/model/coreos/cloud-config.erb
core/model/coreos/cloud_config_in_memory.erb
core/model/coreos/kernel_args_in_memory.erb
core/model/coreos_in_memory.rb
core/model/coreos_stable.rb
core/model/in_memory.rb
core/model/model_dep.rb
util/utility.rb

This PR adds a new `CoreosInMemory` model to Hanlon (which extends a new `InMemory` model type, which itself extends the `Base` model type). We've also added a new pair of methods to the `Utility` module used across Hanlon that can be used to convert a BSON::OrderedHash (the data type returned from MongoDB to Hanlon) to a regular Ruby Hash. This method is needed to create a 'clean' YAML for use as the `cloud-config` that is passed into the CoreOS instance that a node boots into when bound to the new `CoreosInMemory` model. Without this method, the cloud-config passed through to the CoreOS instance looks like this:
```yaml
#cloud-config
--- !ruby/hash:BSON::OrderedHash
coreos: !ruby/hash:BSON::OrderedHash
units:
- !ruby/hash:BSON::OrderedHash
name: etcd.service
command: start
- …
```

Adds an "in-memory" CoreOS model to Hanlon

---

core/model/coreos.rb
core/model/coreos/kernel_args.erb
core/model/coreos/kernel_args_in_memory.erb
core/model/coreos_in_memory.rb
core/model/in_memory.rb

The changes in this PR modify the "CoreOS In-memory" model so that once node finishes booting into an in-memory CoreOS instance for the first time it is transitioned to a "complete" state.
This PR also includes a small fix to the "CoreOS" model that is extended by the "CoreOS Standard" model that was similar to the fix we made to the "CoreOS In-memory" model to ensure we don't try to pass the YAML version of a BSON OrderedHash to the underlying CoreOS instance as it's cloud-config (making it unusable by the CoreOS instance) and a couple of small changes to that same model so that we can minimize the amount of code duplication in our ERB templates for these two related models (the standard and in-memory CoreOS models).
With these changes in place, the CoreOS in memory model now transitions …

Fixes #363 (coreos_in_memory stays in init state, even when it's up with no broker)

---

core/config/server.rb

The changes in this pull request add the commands to the Facter::Util::IP module that we've customized for use in the `ProjectHanlon::Config::Server` class. With these changes, this class now supports the use of the `ip` command instead of the `ifconfig` command on systems where the `ifconfig` command is not available. In fact, we now use the `ip` command by default, and only attempt to use the `ifconfig` command if the `ip` command is not available. This should resolve the issue referenced above.

Fixes #362 (If ifconfig unavailable hanlon_init fails)

---

Dockerfile
README.md
hanlon.gemspec

Recent changes to the Dockerfile require a new tag to ensure that the new Dockerfile is used in the dockerhub build...

Preparing to tag for a v2.3.0 release

---

core/engine.rb
core/node.rb
core/rebind_request.rb
core/slice.rb
core/slice/node.rb
web/api/api_node_v1.rb

This PR adds a new "rebind" action to the node slice.  When you "set" a rebinding request, Hanlon will boot the node into the appropriate in-memory model on the next reboot, then boot back into the bound active_model after that.
An in-memory model is considered to be "appropriate" if the node would bind to it based on the tags assigned to that node and the tags for that in-memory model. The rules for that "rebinding" are the same as those that would be followed in binding the node to any other model via the policy table, except that only in-memory models are considered during this rebinding process.
Once the node has been "rebound" to an existing in-memory model, the rebinding request for that node will be removed from the system. If no in-memory model exists that the node can bind to, …

Adding ability to rebind a node to an in-memory model (temporarily)

---

web/api/api_image_v1.rb

The changes in this PR return a proper error in these situations rather than returning the rather generic (and incorrect error) that was returned previously. Specifically, prior to the changes in this PR, attempts to access a partial path to an image resource or to access a non-existent resource under an image path would result in an error that looked something like this being thrown:
```json
{
"response": {
"result": {
"code": 500,
"type": "NameError",
"description": "undefined local variable or method `logger' for #<Grape::Endpoint:0x00000002d98210>"
}
}
}
```
This error was the result of an attempt to use the non-existent `logger` object when reporting the actual error that occured, an object that is undefined in the context of the Grape endpoint in question (the image endpoint). With …

Fixes #40 (Access to partial image paths should return a proper error)

---

core/engine.rb
core/policy/boot_mk.rb

Prior to the changes in this PR, users who attempted to boot an unknown node against Hanlon would receive a fairly hard to interpret "parse error" in the console as the node iPXE-booted against Hanlon if they had forgotten to add a Microkernel image to Hanlon before doing so. This was because the output of such a request was a JSON response containing a rather cryptic error rather than a proper iPXE-boot script:
```json
{
"response": {
"result": {
"code": 500,
"type": "NoMethodError",
"description": "undefined method `uuid' for nil:NilClass"
}
}
}
```
The changes in this PR add an error-handling PXE-boot script to Hanlon that will echo out the fact that a Microkernel could not be found, then sleep the node for 30 seconds, and then reboot it. This error-handling script will be returned …

Fixes #358 (Inform that an mk is needed rather than return undefined method `uuid' for nil)

---

core/slice/model.rb
web/api/api_model_v1.rb

The issue referenced above is actually somewhat misleading.  The problem is actually that without the changes in this PR Hanlon tells the user that the image used when attempting to create an OS model using a MK image cannot be found, as can be seen in this output:
```bash
[root@ubuntu-server Hanlon (master ✗)]$ hanlon model add -t redhat_6 -l "test model" -o rhel6-model.yaml -i 1cW7cFPodqlUAnAHPkBqeO
--- Building Model (redhat_6):
[model] [add_model] <-Invalid Image UUID [1cW7cFPodqlUAnAHPkBqeO]
Command help:
hanlon model add (options...)
-t, --template MODEL_TEMPLATE            The model template to use for the new model.
-l, --label MODEL_LABEL                  The label to use for the new model.
-i, --image-uuid IMAGE_UUID              The image UUID to use for the new model.
-o, …
```

Fixes #32 (Attempting to construct model with MK throws an exception)

---

core/slice.rb
core/slice/active_model.rb
core/slice/node.rb
web/api/api_active_model_v1.rb
web/api/api_node_v1.rb

The changes in this pull request add the ability to retrieve a list of active_models based on the policy that was used to create them or a list of nodes based on the policy that was used to create the active_model instances that are bound to them. From the CLI, this change shows up as a new option to the `get_all_active_models` and `get_all_nodes` methods, as can be seen, below:
```bash
$ hanlon active_model get all --help
Usage: hanlon active_model [get] [all] (options...)
-o, --policy POLICY_UUID         Show only nodes bound by this policy instance
-h, --help                       Display this screen.
$ hanlon node get all --help
Usage: hanlon node [get] [all] (options...)
-o, --policy POLICY_UUID         Show only nodes bound by this policy instance
-h, --help …
```

Resolves #352 (Given a policy, retrieve it's active_model and nodes)

---

core/node.rb
core/slice.rb
core/slice/node.rb

The changes in this PR add an additional flag to the `hanlon node get all ...` CLI command that provides the user with the ability to specify additional attributes that they would like to include in the CLI output of that command:
```bash
$ hanlon node get all --help
Usage: hanlon node [get] [all] (options...)
-o, --policy POLICY_UUID         Show only nodes bound by this policy instance
-a, --attribs ATTRIBS_LIST       Show additional attributes from ATTRIBS_LIST in output
-h, --help                       Display this screen.
$ 
```
The new flag (the `-a` or `--attribs` flag) takes a single argument, which is assumed to be a comma-separated list of attributes that should be appended to the normal output for this command (which, by default, shows the UUID of the node, the elapsed time …

Resolves #359 (hanlon node option for --list-by-hw-id)

---

Gemfile

The changes in this PR set the version of Ruby declared in the Gemfile declared to match the version declared in the Dockerfile (otherwise the docker build fails with an error because bundler cannot be run on newer versions of the ruby:2.2-wheezy container). We could have done this either by specifying a less-specific version of Ruby in the Gemfile or a more-specific version of Ruby in the Dockerfile; we chose to do the former over the latter.

Set Gemfile declared version of Ruby to match the Dockerfile

---

Dockerfile
Gemfile

Set Gemfile declared version of ruby and Dockerfile declared version of ruby to match, down to the minor build number (otherwise the docker build fails with an error because bundler cannot be run on newer versions of the ruby:2.2.2-wheezy container

Set Gemfile declared version of Ruby to match the Dockerfile (take 2)

---

web/api/api_policy_v1.rb

Updates policy table so that UUIDs of any policies that are removed from the system are also removed from the list of UUIDs maintained in the policy table.
Previous to this change the policy table continued to grow as additional policies were added (even if the policies that should have been removed were filtered out later, we definitely should keep the policy table UUID list clean as we remove policies).

Update policy table when policies are removed

---

core/model/esxi/5/kickstart.erb
core/model/esxi/5_dhcp/kickstart.erb
core/model/redhat.rb
core/model/redhat/6/kickstart.erb
core/model/redhat/7/kickstart.erb
core/model/vmware_esxi.rb
scripts/minimize-rhel-iso.sh

This PR adds the ability to specify a custom partitioning scheme in the Red Hat model.  If one is not specified, `autopart` is used as default as it was previously.
An example optional yaml file:
```
---
hostname_prefix: node
domainname: localdomain
root_password: test1234
partition_scheme: |
part /boot --ondisk=sda --size=512  --fstype=ext3
part swap  --ondisk=sda --size=4096 --fstype=swap
part pv.01 --ondisk=sda --size=1 --grow
volgroup vg_root pv.01
logvol / --vgname=vg_root --size=32768 --name=lv_root --fstype=xfs --grow
ignoredisk --only-use=sda
```
Other changes:
* The `--initlabel` option is deprecated in RHEL 7 and has been removed from the kickstart.
* The kickstarts for esxi were updated to ensure that all partitions are cleared prior to an installation.
* Various minor file …

Adding an option for custom Red Hat partitioning

---

core/policies.rb
core/slice/policy.rb
web/api/api_policy_v1.rb

The changes in this pull request give users the ability to specify the line number in the policy rules table that should be used for a new policy when it is being created. Previously, this would require creating a new policy (which would be placed at the end of the policy rules table by default), then moving that policy to the line number the where it should be placed. Now this same sequence of operations can be completed in one POST to the policy endpoint. For example, let's assume that the policy table for your system looks something like this:
```bash
$ hanlon policy
Policies:
0  true     coreos-607.0.0               [564DC8E3-22AC-0D46-6001-50B003AECE0B]  coreos-607.0.0               2/-    2        2R4R4wfL4hxCYNPQKRGTXU
1  true     rhel-server-7.0-x86_64       [memsize_2GiB,cpus_2] …
```

Specify line number when creating a new policy

---

core/model/coreos.rb
core/model/redhat.rb

The opt_metadata_hash was not being returned through the API and was
causing a failure when trying to supply the partition_scheme parameter.

Correcting the redhat model to fix opt_metadata_hash

---

core/engine.rb
core/policies.rb
core/policy/base.rb
core/policy/boot_local.rb
core/policy/discover_only.rb
core/policy/no_op.rb
core/slice/policy.rb
web/api/api_policy_v1.rb

The changes in this pull request add a new concept to Hanlon, that of a "default policy".  The intent of adding a default policy to the policy rules table is to provide users with a mechanism for creating a policy that will match any node, regardless of how it is tagged, if no other policies in the policy rules table match.  There are a number of restrictions on default policies that are imposed by the code in this pull request, namely:
* there can only be one default policy in the system at a time; any attempt to add a second default policy will result in an error being thrown
* that default policy can only be created using a "noop policy" template (either a `discover_only` or a `boot_local` policy template); attempts to create a default policy based on any other type of policy will fail …

Adds the concept of a 'default policy' to Hanlon

---

web/api/api_node_v1.rb

The changes in this PR fix the code used to select the IPMI options passed into into the `get_power_status` command. Prior to this PR, the code attempted to select out these parameters as Symbols (resulting in an empty Hash map). They should be selected as Strings instead (which is what this code does).

Fixes attempt to select IPMI options when getting power status

---

Dockerfile
docker-entrypoint.sh
hanlon_init

Adding modifications that @tjmcs wrote in hanlon_init
Added docker-entrypoint.sh
Changed Dockerfile to for ENTRYPOINT and COPY of docker-entrypoint.sh
This allows parameters to be passed to puma for threading and workers

Changes Docker to support cassandra

---

core/slice/node.rb
web/api/api_node_v1.rb

adds an option for specifying IPMI options to the get power state and update the power state of a node

Fixes #394 (Options for IPMI commands)

---

core/slice/active_model.rb

It is much more sane to sort on 'label' instead of 'node_uuid'.

Updating Active Model CLI sort order

---

web/api/api_active_model_v1.rb
web/api/api_broker_v1.rb
web/api/api_image_v1.rb
web/api/api_model_v1.rb
web/api/api_node_v1.rb
web/api/api_policy_v1.rb
web/api/api_tag_v1.rb
web/api/api_utils.rb

The changes in this PR add an optional `filter_str` parameter to the `GET` methods of the RESTful APIs for the set of slices that are meant to be invoked by Hanlon users. Users can use this `filter_str` parameter to filter the set of object references (URIs) that will be returned from the `GET` operation to just those that. This new filter query parameter was added to the following endpoints:
* /active_model
* /broker
* /image
* /model
* /node
* /policy
* /tag
* tag/{UUID}/matcher
The value for the `filter_str` parameter is assumed to be a URI-encoded string (since it appears as part of the URI for the `GET`), and the value is assumed to be one or more `name=value` pairs separated by a `+` character. The result of the `GET` operation is then searched for objects who's `name` parameter …

Resolves #399 (API Get objects using filter doesn't work)

---

web/api/api_node_v1.rb

This PR includes the changes needed to ensure that SMBIOS UUIDs used by Hanlon to identify a node in any of the node commands are all compared as upper-case strings (regardless of whether they were passed in as upper-case only or mixed/lower-case) by "upcasing" all of them when they are extracted from any requests made against the node slice's RESTful API

Fixes #401 (Node API does not correctly handle letter case for hw_id)

---

test/spec/web/api/api_node_spec.rb
web/api/api_node_v1.rb

This commit adds a couple of checks to make sure the SMBIOS UUID is properly handled when nodes are added and queried.  Also, it didn't make sense to return `get_all_nodes` as the command when we were returning a single node based on hw_id.

Updating rspec tests to verify SMBIOS UUID

---

core/config/server.rb

- fixes incorrect netmask extraction.

Fixes #407 (Code used to gather netmask information for interfaces that are down fails unexpectedly)

---

core/image_service/base.rb
web/api/api_image_v1.rb

When adding a new image, Hanlon (by default) attempts to unpack the image ISO file using the `fuseiso` or `7z` commands (in that order). If neither of those commands can be found, then it attempts to unpack the ISO file by mounting it (using the standard `mount` command) and then copying over the contents to a directory under the Hanlon image repository.
The issue this PR resolves involved the edge case where neither the `fuseiso` nor the `7z` command were available and the Hanlon was being run as a non-root user. In those situations, the command by Hanlon run to mount the ISO file is the `sudo -n mount` command, and if there is a password required to run this command as that non-root user, then an error is thrown by that command. Unfortunately, the end-user would have no idea what the …

Fixes #405 (Adding an image as a non-root user using the mount command fails unexpectedly)

---

core/slice/image.rb
hanlon.gemspec

requires were alphabetized
quoted string literals were switched from double quotes to single quotes
get_foo_version_info refactored to get_docker_version_info and get_docker_version_from_tar

method extraction

---

core/slice/image.rb

Fixes a bug introduced in PR #414 when @Suirtimed replaced the double quotes around the newline string in a `gsub()` call with single quotes. As a result, the newline at the end of the `file` command output that is used to obtain the mime type was not substituted with an empty string and the result (eg. "bzip2\n" for a bzip2 file) doesn't match any of the keys in our new `SUPPORTED_TYPES` array and an error is thrown when it shouldn't be. The changes in this PR switch that string back to a double-quoted string, so the` gsub()` call succeeds and a match is found to one of the supported types.
Prior to the fix in this PR, this is what Hanlon output when I tried to add a Microkernel image:
```bash
$ hanlon image add -t mk -p /tmp/rancheros-v0.4.1.iso -d /tmp/cscdock-mk-image.tar.bz2 -k …
```

Fixes double-quote to single-quote bug introduced in a recent PR

---

core/slice/image.rb

This PR adds error handling to the new `hanlon image add` code (so that errors are caught and reported properly to CSC). Feedback is welcome!

Fixes #409 (Add error handling to new 'microkernel add' code)

---

scripts/winpe/hanlon-discover.ps1

This PR should resolve the issue #419.
Modified script to flip the byte order of the smbios uuid when using VirtualBox or VMware virtual machines.  End to end testing has not been done, only executing the script from a local PowerShell.

Fixes #419 (issue with smbios UUID in some hypervisors)

---

.dockerignore
docker-compose.yml
hanlon.env

The Hanlon container requires three other services to run.
The database, typically mongo, tftp and DHCP.  We have created a
container for tftp and use mongo's already available container
on Docker registry.  DHCPd is just easier at this point to run on
the host or an externally so that is not included.
This docker-compose addition will orchestrate the starting of the
required services for Hanlon.
We also added a `.dockerignore` so the container build process
removes those unneeded files.
Show running `docker-compose`
```bash
root@ubuntu-hanlon:~/Hanlon# docker-compose up -d
Creating hanlon_mongo_1
Creating hanlon_server_1
Creating hanlon_tftpd_1
root@ubuntu-hanlon:~/Hanlon# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS …
```

Adding docker-compose to automate the containers for Hanlon

---

core/broker/broker_dep.rb
core/broker/salt.rb
core/broker/salt/minion_install.erb
core/model/ubuntu/oneiric/os_boot.erb
core/model/ubuntu/oneiric/os_complete.erb
core/model/ubuntu/precise/os_boot.erb
core/model/ubuntu/precise/os_complete.erb
core/model/ubuntu/precise_ip_pool/os_boot.erb
core/model/ubuntu/precise_ip_pool/os_complete.erb
core/model/ubuntu/quantal/os_boot.erb
core/model/ubuntu/quantal/os_complete.erb
core/model/ubuntu/raring/os_boot.erb
core/model/ubuntu/raring/os_complete.erb
core/model/ubuntu/trusty/os_boot.erb
core/model/ubuntu/trusty/os_complete.erb
core/model/ubuntu/vivid/os_boot.erb
core/model/ubuntu/vivid/os_complete.erb
core/model/ubuntu/xenial/os_boot.erb
core/model/ubuntu/xenial/os_complete.erb

Here is the completed Salt broker that I started a few months back. Finally had time to tidy it up. 
It is based off the Puppet plugin. I have also rewritten how os_boot.erb is structured (at least in the Ubuntu OSes) to provide more logging/debug information. All the logs are now written to /root so that they survive any cleanups that may occur in /tmp. Part of this is so that one can go back and investigate the lineage of the OS install and/or look for installation errors. 
Another change to the code outside of the Salt plugin proper was updating os_boot.erb to delay after setting the hostname. While debugging why on some systems the os_boot script would complete successfully while on others it would act as if it was disconnected from the network, I found that some NIC drivers need a …

Salt Broker
